services:
  client:
    container_name: client
    build:
      context: ./
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    volumes:
      - caddy_srv:/app/build

volumes:
  caddy_srv:
    external: true
